# .github/workflows/snake.yml

name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo so GitHub has access to write to dist/
      - name: Checkout your repo
        uses: actions/checkout@v3

      # Step 2: Generate the snake SVG
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: aryas004
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Step 3: Push the output to a branch called "output"
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
